version: '3.4'

services:
  app:
    environment:
      ENV: localdev
      PORT: 8000
    restart: always
    container_name: app-handshake
    build:
      context: .
      target: app-container
    volumes:
      - ./sis_provisioner:/app/sis_provisioner
    ports:
      - "8000:8000"
