ingress:
  enabled: false
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
securityPolicy:
  enabled: true
repo: handshake
instance: test
image:
  repository: gcr.io/uwit-mci-axdd/handshake
  tag: IMAGE_TAG
memcached:
  enabled: true
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
cronjob:
  enabled: false
gcsCredentials:
  mounted: true
  secretName: test.handshake.uw.edu-gcs-credentials

environmentVariables:
  - name: ENV
    value: test

  - name: SESSION_BACKEND
    value: MEMCACHED

externalSecrets:
  enabled: true
  secrets:
    - name: test.handshake.uw.edu-secrets
      externalKey: axdd/kv/data/handshake/test/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: storage-bucket-name
          property: storage-bucket-name
    - name: test.handshake.uw.edu-shared-secrets
      externalKey: axdd/kv/data/handshake/shared/secrets
      data:
        - name: storage-project-id
          property: storage-project-id
    - name: test.handshake.uw.edu-gcs-credentials
      externalKey: axdd/kv/data/handshake/shared/gcs-credentials
      data:
        - name: credentials.json
          property: credentials.json
    - name: test.handshake.uw.edu-aws-secrets
      externalKey: axdd/kv/data/handshake/shared/aws-secrets
      data:
        - name: access-key-id
          property: access-key-id
        - name: secret-access-key
          property: secret-access-key
        - name: storage-bucket-name
          property: storage-bucket-name

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test.handshake.uw.edu-secrets
    secretKey: django-secret
  storageBucketName:
    name: STORAGE_BUCKET_NAME
    secretName: test.handshake.uw.edu-secrets
    secretKey: storage-bucket-name
  storageProjectId:
    name: STORAGE_PROJECT_ID
    secretName: test.handshake.uw.edu-shared-secrets
    secretKey: storage-project-id
  awsStorageBucketName:
    name: AWS_STORAGE_BUCKET_NAME
    secretName: test.handshake.uw.edu-aws-secrets
    secretKey: storage-bucket-name
  awsAccessKeyID:
    name: AWS_S3_ACCESS_KEY_ID
    secretName: test.handshake.uw.edu-aws-secrets
    secretKey: access-key-id
  awsSecretAccessKey:
    name: AWS_S3_SECRET_ACCESS_KEY
    secretName: test.handshake.uw.edu-aws-secrets
    secretKey: secret-access-key

