# Generated by Django 3.2.16 on 2022-10-26 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveStudentsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128, null=True)),
                ('created_by', models.CharField(default='internal', max_length=32)),
                ('created_date', models.DateTimeField()),
                ('generated_date', models.DateTimeField(null=True)),
                ('import_progress', models.SmallIntegerField(default=0)),
                ('imported_date', models.DateTimeField(null=True)),
                ('imported_status', models.CharField(max_length=128, null=True)),
                ('process_id', models.CharField(max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FosterStudentsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128, null=True)),
                ('created_by', models.CharField(default='internal', max_length=32)),
                ('created_date', models.DateTimeField()),
                ('generated_date', models.DateTimeField(null=True)),
                ('import_progress', models.SmallIntegerField(default=0)),
                ('imported_date', models.DateTimeField(null=True)),
                ('imported_status', models.CharField(max_length=128, null=True)),
                ('process_id', models.CharField(max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HandshakeStudentsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128, null=True)),
                ('created_by', models.CharField(default='internal', max_length=32)),
                ('created_date', models.DateTimeField()),
                ('generated_date', models.DateTimeField(null=True)),
                ('import_progress', models.SmallIntegerField(default=0)),
                ('imported_date', models.DateTimeField(null=True)),
                ('imported_status', models.CharField(max_length=128, null=True)),
                ('process_id', models.CharField(max_length=64, null=True)),
                ('is_test_file', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('quarter', models.SmallIntegerField(choices=[(1, 'WIN'), (2, 'SPR'), (3, 'SUM'), (4, 'AUT')])),
            ],
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('year', 'quarter'), name='unique_term'),
        ),
        migrations.AddField(
            model_name='handshakestudentsfile',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_provisioner.term'),
        ),
        migrations.AddField(
            model_name='fosterstudentsfile',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_provisioner.term'),
        ),
    ]
