# Generated by Django 3.2.15 on 2022-09-21 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128, null=True)),
                ('is_test_file', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField()),
                ('processed_date', models.DateTimeField(null=True)),
                ('processed_status', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('quarter', models.SmallIntegerField(choices=[(1, 'WIN'), (2, 'SPR'), (3, 'SUM'), (4, 'AUT')])),
            ],
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('year', 'quarter'), name='unique_term'),
        ),
        migrations.AddField(
            model_name='importfile',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_provisioner.term'),
        ),
    ]
