# Generated by Django 3.2.15 on 2022-08-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
