# Generated by Django 3.2.16 on 2022-11-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activestudentsfile',
            name='created_by',
            field=models.CharField(default='automatic', max_length=32),
        ),
        migrations.AlterField(
            model_name='fosterstudentsfile',
            name='created_by',
            field=models.CharField(default='automatic', max_length=32),
        ),
        migrations.AlterField(
            model_name='handshakestudentsfile',
            name='created_by',
            field=models.CharField(default='automatic', max_length=32),
        ),
    ]
