# Generated by Django 3.2.15 on 2022-09-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='created_by',
            field=models.CharField(default='internal', max_length=32),
        ),
        migrations.AddField(
            model_name='importfile',
            name='import_progress',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importfile',
            name='process_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
