# Generated by Django 3.2.16 on 2022-11-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0002_auto_20221101_1606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FosterStudentsFile',
        ),
    ]
