# Generated by Django 3.2.18 on 2023-04-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0003_delete_fosterstudentsfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedHandshakeStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('added_by', models.CharField(max_length=20)),
                ('added_date', models.DateTimeField()),
                ('reason', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
