# Generated by Django 4.2.7 on 2023-11-29 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0005_handshakelabelsfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='handshakelabelsfile',
            name='created_by',
            field=models.CharField(default='automatic', max_length=32),
        ),
        migrations.AddField(
            model_name='handshakelabelsfile',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handshakelabelsfile',
            name='generated_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='handshakelabelsfile',
            name='import_progress',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='handshakelabelsfile',
            name='imported_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='handshakelabelsfile',
            name='imported_status',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='handshakelabelsfile',
            name='path',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='handshakelabelsfile',
            name='process_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
