# Generated by Django 5.2.13 on 2026-05-15 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0006_handshakelabelsfile_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UconnectStudentsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128, null=True)),
                ('created_by', models.CharField(default='automatic', max_length=32)),
                ('created_date', models.DateTimeField()),
                ('generated_date', models.DateTimeField(null=True)),
                ('import_progress', models.SmallIntegerField(default=0)),
                ('imported_date', models.DateTimeField(null=True)),
                ('imported_status', models.CharField(max_length=128, null=True)),
                ('process_id', models.CharField(max_length=64, null=True)),
                ('is_test_file', models.BooleanField(default=False)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_provisioner.term')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
