# Generated by Django 5.2.13 on 2026-05-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_provisioner', '0007_uconnectstudentsfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUconnectStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('added_by', models.CharField(max_length=20)),
                ('added_date', models.DateTimeField()),
                ('reason', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
